apiVersion: apps/v1
kind: Deployment
metadata:
  name: armando-deployment
  namespace: Hadi
spec:
  selector:
    matchLabels:
      app: armando
  replicas: 2
  template:
    metadata:
      labels:
        app: armando
    spec:
      containers:
        - name: armando
          image: armando:1.1.0  
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          ports:
          - containerPort: 8080
          env:
           - name: MARADONA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: maradona-secret
                  key: auth_secret_key
            - name: ARMANDO_HTTP_SERVER_GRACEFUL_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: armando-special-config
                  key: http_server.graceful_timeout
            - name: ARMANDO_CONFIG_FILE_PATH
              value: /file-config.yml
               name: ARMANDO_STATIC_PATH
              value: /var/static-files
          volumeMounts:
            - name: armando-volume
              mountPath: /file-config.yml
              subPath: configuration.yml
               name: armando-pv-storage
              mountPath: "/var/static-files"
      volumes:
        - name: armando-volume
          configMap:
            name: armando-file-config
        - name: armando-pv-storage
          persistentVolumeClaim:
            claimName: armando-pv-claim