apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: armando-pv-claim
  namespace: Hadi
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi